import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :messaging_spike, MessagingSpikeWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :messaging_spike, MessagingSpikeWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :messaging_spike, MessagingSpikeWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

config :messaging_spike, MessagingSpike.Brokers.Rabbit,
  host: System.get_env("RABBIT_HOST"),
  port: System.get_env("RABBIT_PORT"),
  username: System.get_env("RABBIT_USER"),
  password: System.get_env("RABBIT_PASS")

config :messaging_spike, MessagingSpike.Brokers.Nats,
  host: System.get_env("NATS_HOST"),
  port: System.get_env("NATS_PORT"),
  username: System.get_env("NATS_USER"),
  password: System.get_env("NATS_PASS")

# config :kafka_ex,
#   brokers: [
#     {"#{System.get_env("KAFKA_HOST")}:#{System.get_env("KAFKA_PORT")}"}
#   ]

config :messaging_spike, MessagingSpike.Brokers.Redis,
  host: System.get_env("REDIS_HOST"),
  port: System.get_env("REDIS_PORT"),
  username: System.get_env("REDIS_USER"),
  password: System.get_env("REDIS_PASS")
